@startuml
'https://plantuml.com/class-diagram

class Réaliser {
-idUtilisateur
-idTypeAction
-date/heure
}

class TypeAction {
-idTypeAction
libellé
}

class Utilisateur{
-idUtilisateur
}

Réaliser -- Utilisateur
Réaliser -- TypeAction

@enduml